package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbbranch;

public interface TbbranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbbranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbbranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbbranch selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbbranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbranch
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbbranch record);
}