package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbform;

public interface TbformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbform selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbform
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbform record);
}