package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbformitem;

public interface TbformitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer fmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbformitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbformitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbformitem selectByPrimaryKey(Integer fmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbformitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbformitem
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbformitem record);
}