package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbprojrank;

public interface TbprojrankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbprojrank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbprojrank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbprojrank selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbprojrank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojrank
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbprojrank record);
}