package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbprojscores;

public interface TbprojscoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer scsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbprojscores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbprojscores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbprojscores selectByPrimaryKey(Integer scsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbprojscores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscores
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbprojscores record);
}