package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbprojgrp;

public interface TbprojgrpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbprojgrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbprojgrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbprojgrp selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbprojgrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojgrp
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbprojgrp record);
}