package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbprojscore;

public interface TbprojscoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbprojscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbprojscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbprojscore selectByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbprojscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprojscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbprojscore record);
}