package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbstfm;

public interface TbstfmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer sfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbstfm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbstfm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbstfm selectByPrimaryKey(Integer sfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbstfm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstfm
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbstfm record);
}