package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbstaff;

public interface TbstaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbstaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbstaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbstaff selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbstaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbstaff
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbstaff record);
}