package abc.tzous4j.kpsys.dao;

import abc.tzous4j.kpsys.model.Tbsys;

public interface TbsysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(Integer sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbsys selectByPrimaryKey(Integer sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbsys record);
}