package abc.tzous4j.kpsys.dao;

import java.util.HashMap;
import java.util.List;

import abc.tzous4j.kpsys.model.Tbuser;

public interface TbuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int deleteByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insert(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int insertSelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    Tbuser selectByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    int updateByPrimaryKey(Tbuser record);
    int countAll();
    public List<Tbuser> findTbuserAll();
    public List<Tbuser> findTbuser(HashMap<String, Integer> offsetLimit);


}