package abc.tzous4j.kpsys.model;

public class Tbbranch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbranch.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbranch.bname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbranch.bhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer bhid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbranch.bstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer bstat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbranch.bid
     *
     * @return the value of tbbranch.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbranch.bid
     *
     * @param bid the value for tbbranch.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbranch.bname
     *
     * @return the value of tbbranch.bname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbranch.bname
     *
     * @param bname the value for tbbranch.bname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbranch.bhid
     *
     * @return the value of tbbranch.bhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getBhid() {
        return bhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbranch.bhid
     *
     * @param bhid the value for tbbranch.bhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setBhid(Integer bhid) {
        this.bhid = bhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbranch.bstat
     *
     * @return the value of tbbranch.bstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getBstat() {
        return bstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbranch.bstat
     *
     * @param bstat the value for tbbranch.bstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setBstat(Integer bstat) {
        this.bstat = bstat;
    }
}