package abc.tzous4j.kpsys.model;

public class Tbform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbform.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbform.fname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbform.ftype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbform.fhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fhid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbform.fstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fstat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbform.fid
     *
     * @return the value of tbform.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbform.fid
     *
     * @param fid the value for tbform.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbform.fname
     *
     * @return the value of tbform.fname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbform.fname
     *
     * @param fname the value for tbform.fname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbform.ftype
     *
     * @return the value of tbform.ftype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbform.ftype
     *
     * @param ftype the value for tbform.ftype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFtype(Integer ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbform.fhid
     *
     * @return the value of tbform.fhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFhid() {
        return fhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbform.fhid
     *
     * @param fhid the value for tbform.fhid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFhid(Integer fhid) {
        this.fhid = fhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbform.fstat
     *
     * @return the value of tbform.fstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFstat() {
        return fstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbform.fstat
     *
     * @param fstat the value for tbform.fstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFstat(Integer fstat) {
        this.fstat = fstat;
    }
}