package abc.tzous4j.kpsys.model;

public class Tbformitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmnum
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmhtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmhtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmcontent
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String fmcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbformitem.fmdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String fmdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmid
     *
     * @return the value of tbformitem.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmid() {
        return fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmid
     *
     * @param fmid the value for tbformitem.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmid(Integer fmid) {
        this.fmid = fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fid
     *
     * @return the value of tbformitem.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fid
     *
     * @param fid the value for tbformitem.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmnum
     *
     * @return the value of tbformitem.fmnum
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmnum() {
        return fmnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmnum
     *
     * @param fmnum the value for tbformitem.fmnum
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmnum(Integer fmnum) {
        this.fmnum = fmnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmtype
     *
     * @return the value of tbformitem.fmtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmtype() {
        return fmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmtype
     *
     * @param fmtype the value for tbformitem.fmtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmtype(Integer fmtype) {
        this.fmtype = fmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmhtype
     *
     * @return the value of tbformitem.fmhtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmhtype() {
        return fmhtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmhtype
     *
     * @param fmhtype the value for tbformitem.fmhtype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmhtype(Integer fmhtype) {
        this.fmhtype = fmhtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmcontent
     *
     * @return the value of tbformitem.fmcontent
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getFmcontent() {
        return fmcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmcontent
     *
     * @param fmcontent the value for tbformitem.fmcontent
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmcontent(String fmcontent) {
        this.fmcontent = fmcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmscore
     *
     * @return the value of tbformitem.fmscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmscore() {
        return fmscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmscore
     *
     * @param fmscore the value for tbformitem.fmscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmscore(Integer fmscore) {
        this.fmscore = fmscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbformitem.fmdesc
     *
     * @return the value of tbformitem.fmdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getFmdesc() {
        return fmdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbformitem.fmdesc
     *
     * @param fmdesc the value for tbformitem.fmdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmdesc(String fmdesc) {
        this.fmdesc = fmdesc;
    }
}