package abc.tzous4j.kpsys.model;

public class Tbprojrank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String rdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rmode
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.rself
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rself;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojrank.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rid
     *
     * @return the value of tbprojrank.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rid
     *
     * @param rid the value for tbprojrank.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.pid
     *
     * @return the value of tbprojrank.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.pid
     *
     * @param pid the value for tbprojrank.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rname
     *
     * @return the value of tbprojrank.rname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rname
     *
     * @param rname the value for tbprojrank.rname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRname(String rname) {
        this.rname = rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rdesc
     *
     * @return the value of tbprojrank.rdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getRdesc() {
        return rdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rdesc
     *
     * @param rdesc the value for tbprojrank.rdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRdesc(String rdesc) {
        this.rdesc = rdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rscore
     *
     * @return the value of tbprojrank.rscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRscore() {
        return rscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rscore
     *
     * @param rscore the value for tbprojrank.rscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRscore(Integer rscore) {
        this.rscore = rscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rmode
     *
     * @return the value of tbprojrank.rmode
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRmode() {
        return rmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rmode
     *
     * @param rmode the value for tbprojrank.rmode
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRmode(Integer rmode) {
        this.rmode = rmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.rself
     *
     * @return the value of tbprojrank.rself
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRself() {
        return rself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.rself
     *
     * @param rself the value for tbprojrank.rself
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRself(Integer rself) {
        this.rself = rself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojrank.fid
     *
     * @return the value of tbprojrank.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojrank.fid
     *
     * @param fid the value for tbprojrank.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}