package abc.tzous4j.kpsys.model;

public class Tbprojscores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscores.scsid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer scsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscores.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscores.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscores.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscores.scsid
     *
     * @return the value of tbprojscores.scsid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScsid() {
        return scsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscores.scsid
     *
     * @param scsid the value for tbprojscores.scsid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScsid(Integer scsid) {
        this.scsid = scsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscores.scid
     *
     * @return the value of tbprojscores.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscores.scid
     *
     * @param scid the value for tbprojscores.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscores.fmid
     *
     * @return the value of tbprojscores.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFmid() {
        return fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscores.fmid
     *
     * @param fmid the value for tbprojscores.fmid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFmid(Integer fmid) {
        this.fmid = fmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscores.score
     *
     * @return the value of tbprojscores.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscores.score
     *
     * @param score the value for tbprojscores.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}