package abc.tzous4j.kpsys.model;

public class Tbprojscore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.raterid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String raterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.targetid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String targetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojscore.scstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer scstat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.scid
     *
     * @return the value of tbprojscore.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.scid
     *
     * @param scid the value for tbprojscore.scid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.rid
     *
     * @return the value of tbprojscore.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.rid
     *
     * @param rid the value for tbprojscore.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.raterid
     *
     * @return the value of tbprojscore.raterid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getRaterid() {
        return raterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.raterid
     *
     * @param raterid the value for tbprojscore.raterid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRaterid(String raterid) {
        this.raterid = raterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.targetid
     *
     * @return the value of tbprojscore.targetid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.targetid
     *
     * @param targetid the value for tbprojscore.targetid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setTargetid(String targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.score
     *
     * @return the value of tbprojscore.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.score
     *
     * @param score the value for tbprojscore.score
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojscore.scstat
     *
     * @return the value of tbprojscore.scstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getScstat() {
        return scstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojscore.scstat
     *
     * @param scstat the value for tbprojscore.scstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setScstat(Integer scstat) {
        this.scstat = scstat;
    }
}