package abc.tzous4j.kpsys.model;

public class Tbprojgrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojgrp.gid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojgrp.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojgrp.gname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojgrp.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprojgrp.gstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer gstat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojgrp.gid
     *
     * @return the value of tbprojgrp.gid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojgrp.gid
     *
     * @param gid the value for tbprojgrp.gid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojgrp.rid
     *
     * @return the value of tbprojgrp.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojgrp.rid
     *
     * @param rid the value for tbprojgrp.rid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojgrp.gname
     *
     * @return the value of tbprojgrp.gname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojgrp.gname
     *
     * @param gname the value for tbprojgrp.gname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojgrp.sid
     *
     * @return the value of tbprojgrp.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojgrp.sid
     *
     * @param sid the value for tbprojgrp.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprojgrp.gstat
     *
     * @return the value of tbprojgrp.gstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getGstat() {
        return gstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprojgrp.gstat
     *
     * @param gstat the value for tbprojgrp.gstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setGstat(Integer gstat) {
        this.gstat = gstat;
    }
}