package abc.tzous4j.kpsys.model;

public class Tbproj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.pname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.pdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String pdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.ptype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer ptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.pscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer pscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.pstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer pstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproj.period
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String period;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.pid
     *
     * @return the value of tbproj.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.pid
     *
     * @param pid the value for tbproj.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.pname
     *
     * @return the value of tbproj.pname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.pname
     *
     * @param pname the value for tbproj.pname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.pdesc
     *
     * @return the value of tbproj.pdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getPdesc() {
        return pdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.pdesc
     *
     * @param pdesc the value for tbproj.pdesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.ptype
     *
     * @return the value of tbproj.ptype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.ptype
     *
     * @param ptype the value for tbproj.ptype
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPtype(Integer ptype) {
        this.ptype = ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.pscore
     *
     * @return the value of tbproj.pscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPscore() {
        return pscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.pscore
     *
     * @param pscore the value for tbproj.pscore
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPscore(Integer pscore) {
        this.pscore = pscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.pstat
     *
     * @return the value of tbproj.pstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPstat() {
        return pstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.pstat
     *
     * @param pstat the value for tbproj.pstat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPstat(Integer pstat) {
        this.pstat = pstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproj.period
     *
     * @return the value of tbproj.period
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproj.period
     *
     * @param period the value for tbproj.period
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period;
    }
}