package abc.tzous4j.kpsys.model;

public class Tbstbr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstbr.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstbr.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstbr.bid
     *
     * @return the value of tbstbr.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstbr.bid
     *
     * @param bid the value for tbstbr.bid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstbr.sid
     *
     * @return the value of tbstbr.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstbr.sid
     *
     * @param sid the value for tbstbr.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid;
    }
}