package abc.tzous4j.kpsys.model;

public class Tbstfm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstfm.sfid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer sfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstfm.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstfm.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstfm.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstfm.sfid
     *
     * @return the value of tbstfm.sfid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstfm.sfid
     *
     * @param sfid the value for tbstfm.sfid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSfid(Integer sfid) {
        this.sfid = sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstfm.sid
     *
     * @return the value of tbstfm.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstfm.sid
     *
     * @param sid the value for tbstfm.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstfm.pid
     *
     * @return the value of tbstfm.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstfm.pid
     *
     * @param pid the value for tbstfm.pid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstfm.fid
     *
     * @return the value of tbstfm.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstfm.fid
     *
     * @param fid the value for tbstfm.fid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}