package abc.tzous4j.kpsys.model;

public class Tbstaff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstaff.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbstaff.sname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstaff.sid
     *
     * @return the value of tbstaff.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstaff.sid
     *
     * @param sid the value for tbstaff.sid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbstaff.sname
     *
     * @return the value of tbstaff.sname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbstaff.sname
     *
     * @param sname the value for tbstaff.sname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname;
    }
}