package abc.tzous4j.kpsys.model;

public class Tbsys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.sysid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer sysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.sysname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String sysname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.systat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer systat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.sysid
     *
     * @return the value of tbsys.sysid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.sysid
     *
     * @param sysid the value for tbsys.sysid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSysid(Integer sysid) {
        this.sysid = sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.sysname
     *
     * @return the value of tbsys.sysname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getSysname() {
        return sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.sysname
     *
     * @param sysname the value for tbsys.sysname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSysname(String sysname) {
        this.sysname = sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.systat
     *
     * @return the value of tbsys.systat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getSystat() {
        return systat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.systat
     *
     * @param systat the value for tbsys.systat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setSystat(Integer systat) {
        this.systat = systat;
    }
}