package abc.tzous4j.kpsys.model;

import java.util.Date;

public class Tbuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.uname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.uid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.upasswd
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String upasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.ustat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Integer ustat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.udesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private String udesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.uregister
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Date uregister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.uinvalid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    private Date uinvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.uname
     *
     * @return the value of tbuser.uname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.uname
     *
     * @param uname the value for tbuser.uname
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.uid
     *
     * @return the value of tbuser.uid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.uid
     *
     * @param uid the value for tbuser.uid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.upasswd
     *
     * @return the value of tbuser.upasswd
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getUpasswd() {
        return upasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.upasswd
     *
     * @param upasswd the value for tbuser.upasswd
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUpasswd(String upasswd) {
        this.upasswd = upasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.ustat
     *
     * @return the value of tbuser.ustat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Integer getUstat() {
        return ustat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.ustat
     *
     * @param ustat the value for tbuser.ustat
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUstat(Integer ustat) {
        this.ustat = ustat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.udesc
     *
     * @return the value of tbuser.udesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public String getUdesc() {
        return udesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.udesc
     *
     * @param udesc the value for tbuser.udesc
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUdesc(String udesc) {
        this.udesc = udesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.uregister
     *
     * @return the value of tbuser.uregister
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Date getUregister() {
        return uregister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.uregister
     *
     * @param uregister the value for tbuser.uregister
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUregister(Date uregister) {
        this.uregister = uregister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.uinvalid
     *
     * @return the value of tbuser.uinvalid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public Date getUinvalid() {
        return uinvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.uinvalid
     *
     * @param uinvalid the value for tbuser.uinvalid
     *
     * @mbg.generated Sat Jan 05 20:22:38 CST 2019
     */
    public void setUinvalid(Date uinvalid) {
        this.uinvalid = uinvalid;
    }
}